image: Visual Studio 2017

branches:
  only:
    - master
    - develop

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

before_build:
  - cd src
  - nuget restore

build:
  project: src/Spk.UnhandledExceptionHandler.sln
  publish_nuget: true   

artifacts:
  - path: '**\*.nupkg'